name: Release
on:
    workflow_dispatch:
      inputs:
        version:
          description: "Release version (e.g. 26.1.0)"
          required: true
          type: string
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v7
        
        - name: Install dependencies
          run: |
            sudo apt install zip
        
        - name: Create assets
          env:
            version: ${{ inputs.version }}
          run: |
            mkdir -p bin
            cd src
            zip -r $(git rev-parse --show-toplevel)/bin/NoRocketUsage-${version}.zip *
        
        - name: Create release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            tag: ${{ inputs.version }}
          run: |
            gh release create "$tag" --repo="$GITHUB_REPOSITORY" --title="${tag}" --generate-notes
        
        - name: Upload assets to GitHub
          uses: AButler/upload-release-assets@v4.0
          with:
            files: "bin/*"
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            release-tag: ${{ inputs.version }}